name: BridingPractice
version: ${project.version}-${git.commit.id.abbrev}
main: dev.aabstractt.bridging.AbstractPlugin
author: bajowkarz

commands:
  islandadmin:
    description: Admin command for the island plugin
    aliases: [isadmin]
    permission: bridging.admin
    permission-message: You do not have permission to use this command